import Head from "next/head";
import { useEffect } from "react";
import { useSelector } from 'react-redux';

import { fetchProducts as fetchHomePageProductsTab, selectAllHomePageProductsTab } from "@/store/features/product/homePageProductsTabSlice";
import { useAppDispatch } from "@/store/store";

export default function Home() {
  const dispatch = useAppDispatch();
  const productsTab = useSelector(selectAllHomePageProductsTab);

  useEffect(() => {
    dispatch(fetchHomePageProductsTab()).then((lastAction) => {
      console.log("lastAction =>", lastAction);
    });
  }, [dispatch]);

  console.log('productsTab =>', productsTab);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <ProductsTabs 
        tabs={[
          { tabName: 'Featured', }
        ]}
        enablePagination
        pageLimit={3}
        fetch={(page: number, limit = 5) => dispatch(fetchHomePageProductsTab({page, limit}))}
        selector={selectAllHomePageProductsTab}
      /> */}
    </>
  );
}
