import Head from "next/head";
import { GetStaticProps, InferGetStaticPropsType } from "next";
import { useEffect } from "react";
import { useSelector } from "react-redux";

import {
  fetchProducts as fetchHomePageProductsTab,
  selectAllHomePageProductsTab,
} from "@/store/features/product/homePageProductsTabSlice";
import { useAppDispatch, useAppSelector } from "@/store/store";
import { useGetHomePageProductsByStatusAndPageQuery } from "@/store/features/api/apiSlice";
import { LayoutProps } from "@/shared/types/layout";
import HomeOneAside from "@/components/sections/home-one-aside/home-one-aside";
import { ComponentNames } from "@/shared/types/components";
import { TabPanel } from "@/components/ui/tabs/tab-panel";

type Props = {
  layout: LayoutProps;
};

export default function Home(
  props: InferGetStaticPropsType<typeof getStaticProps>
) {
  // const dispatch = useAppDispatch();
  // const productsTab = useAppSelector(selectAllHomePageProductsTab);

  /*   useEffect(() => {
    dispatch(fetchHomePageProductsTab()).then((lastAction) => {
      console.log("lastAction =>", lastAction);
    });
  }, [dispatch]); */

  const { data, isLoading, isSuccess } =
    useGetHomePageProductsByStatusAndPageQuery({});

  console.log("productsTab =>", data);
  console.log("isSuccess =>", isSuccess);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Homeeee</h1>
      {/* only testing */}
      <TabPanel value="1" sx={}>
        <h2>Guarda ahiiii</h2>
      </TabPanel>
    </>
  );
}

export const getStaticProps = (async () => {
  return {
    props: {
      layout: {
        type: "oneAside",
        asideComponent: ComponentNames.HomeOneAside,
        side: "left",
        asideFr: 1,
        mainFr: 1,
      },
    },
  };
}) satisfies GetStaticProps<Props>;
